image: node:alpine

stages:
    - prepare
    - build
    - deploy

node:install:
    stage: prepare
    script:
        - npm i
    cache:
        key: $CI_COMMIT_REF_SLUG
        paths:
            - node_modules/
        policy: pull-push
    artifacts:
        paths:
            - node_modules/

build:
    stage: build
    script:
        - npm run build
    cache:
        key: $CI_COMMIT_REF_SLUG
        paths:
            - node_modules/
    artifacts:
        paths:
            - build/

docker:deploy:latest:
    only:
        - prod
    stage: deploy
    image:
        name: docker/compose:1.28.2
        entrypoint: ["/bin/sh", "-c"]
    script:
        - docker-compose -f moneyboy-docker/docker-compose.yml build
        - docker-compose -f moneyboy-docker/docker-compose.yml up -d
    cache:
        key: $CI_COMMIT_REF_SLUG
        paths:
            - node_modules/
        policy: pull-push
